// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package protobuf.order;

public final class Order {
  private Order() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   **
   *Tipo da transação.
   * </pre>
   *
   * Protobuf enum {@code order.OrderRequestType}
   */
  public enum OrderRequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BUY = 0;</code>
     */
    BUY(0),
    /**
     * <code>SELL = 1;</code>
     */
    SELL(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>BUY = 0;</code>
     */
    public static final int BUY_VALUE = 0;
    /**
     * <code>SELL = 1;</code>
     */
    public static final int SELL_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OrderRequestType valueOf(int value) {
      return forNumber(value);
    }

    public static OrderRequestType forNumber(int value) {
      switch (value) {
        case 0: return BUY;
        case 1: return SELL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OrderRequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OrderRequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OrderRequestType>() {
            public OrderRequestType findValueByNumber(int number) {
              return OrderRequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protobuf.order.Order.getDescriptor().getEnumTypes().get(0);
    }

    private static final OrderRequestType[] VALUES = values();

    public static OrderRequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OrderRequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:order.OrderRequestType)
  }

  /**
   * <pre>
   **
   *Tipo de resposta
   * </pre>
   *
   * Protobuf enum {@code order.OrderReplyType}
   */
  public enum OrderReplyType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * A transação foi registada 
     * </pre>
     *
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <pre>
     * A transação não foi registada 
     * </pre>
     *
     * <code>NOT_OK = 1;</code>
     */
    NOT_OK(1),
    /**
     * <pre>
     * A empresa não existe 
     * </pre>
     *
     * <code>INVALID_COMPANY = 2;</code>
     */
    INVALID_COMPANY(2),
    /**
     * <pre>
     * O utilizador indicou uma operação que apenas pode fazer
     *se tiver o login feito
     * </pre>
     *
     * <code>NOT_LOGGED_IN = 3;</code>
     */
    NOT_LOGGED_IN(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * A transação foi registada 
     * </pre>
     *
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <pre>
     * A transação não foi registada 
     * </pre>
     *
     * <code>NOT_OK = 1;</code>
     */
    public static final int NOT_OK_VALUE = 1;
    /**
     * <pre>
     * A empresa não existe 
     * </pre>
     *
     * <code>INVALID_COMPANY = 2;</code>
     */
    public static final int INVALID_COMPANY_VALUE = 2;
    /**
     * <pre>
     * O utilizador indicou uma operação que apenas pode fazer
     *se tiver o login feito
     * </pre>
     *
     * <code>NOT_LOGGED_IN = 3;</code>
     */
    public static final int NOT_LOGGED_IN_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static OrderReplyType valueOf(int value) {
      return forNumber(value);
    }

    public static OrderReplyType forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return NOT_OK;
        case 2: return INVALID_COMPANY;
        case 3: return NOT_LOGGED_IN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OrderReplyType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OrderReplyType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OrderReplyType>() {
            public OrderReplyType findValueByNumber(int number) {
              return OrderReplyType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protobuf.order.Order.getDescriptor().getEnumTypes().get(1);
    }

    private static final OrderReplyType[] VALUES = values();

    public static OrderReplyType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OrderReplyType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:order.OrderReplyType)
  }

  public interface OrderRequestDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:order.OrderRequestData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Tipo da transação 
     * </pre>
     *
     * <code>.order.OrderRequestType order_type = 1;</code>
     */
    int getOrderTypeValue();
    /**
     * <pre>
     * Tipo da transação 
     * </pre>
     *
     * <code>.order.OrderRequestType order_type = 1;</code>
     */
    protobuf.order.Order.OrderRequestType getOrderType();

    /**
     * <pre>
     * Empresa sobre a qual recai a transação
     * </pre>
     *
     * <code>string company = 2;</code>
     */
    java.lang.String getCompany();
    /**
     * <pre>
     * Empresa sobre a qual recai a transação
     * </pre>
     *
     * <code>string company = 2;</code>
     */
    com.google.protobuf.ByteString
        getCompanyBytes();

    /**
     * <pre>
     * Número de acções a comprar 
     * </pre>
     *
     * <code>int32 qtd = 3;</code>
     */
    int getQtd();

    /**
     * <pre>
     * Preço de compra máximo nas ordens de compra.
     *Preço de compra mínimo nas ordens de venda.
     * </pre>
     *
     * <code>int32 price = 4;</code>
     */
    int getPrice();

    /**
     * <pre>
     * Username de quem fez o pedido
     * </pre>
     *
     * <code>string username = 5;</code>
     */
    java.lang.String getUsername();
    /**
     * <pre>
     * Username de quem fez o pedido
     * </pre>
     *
     * <code>string username = 5;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();
  }
  /**
   * <pre>
   **
   *Mensagem a ser enviada nas ordens de compra e venda.
   * </pre>
   *
   * Protobuf type {@code order.OrderRequestData}
   */
  public  static final class OrderRequestData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:order.OrderRequestData)
      OrderRequestDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OrderRequestData.newBuilder() to construct.
    private OrderRequestData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderRequestData() {
      orderType_ = 0;
      company_ = "";
      qtd_ = 0;
      price_ = 0;
      username_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OrderRequestData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              orderType_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              company_ = s;
              break;
            }
            case 24: {

              qtd_ = input.readInt32();
              break;
            }
            case 32: {

              price_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              username_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.order.Order.internal_static_order_OrderRequestData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.order.Order.internal_static_order_OrderRequestData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.order.Order.OrderRequestData.class, protobuf.order.Order.OrderRequestData.Builder.class);
    }

    public static final int ORDER_TYPE_FIELD_NUMBER = 1;
    private int orderType_;
    /**
     * <pre>
     * Tipo da transação 
     * </pre>
     *
     * <code>.order.OrderRequestType order_type = 1;</code>
     */
    public int getOrderTypeValue() {
      return orderType_;
    }
    /**
     * <pre>
     * Tipo da transação 
     * </pre>
     *
     * <code>.order.OrderRequestType order_type = 1;</code>
     */
    public protobuf.order.Order.OrderRequestType getOrderType() {
      protobuf.order.Order.OrderRequestType result = protobuf.order.Order.OrderRequestType.valueOf(orderType_);
      return result == null ? protobuf.order.Order.OrderRequestType.UNRECOGNIZED : result;
    }

    public static final int COMPANY_FIELD_NUMBER = 2;
    private volatile java.lang.Object company_;
    /**
     * <pre>
     * Empresa sobre a qual recai a transação
     * </pre>
     *
     * <code>string company = 2;</code>
     */
    public java.lang.String getCompany() {
      java.lang.Object ref = company_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        company_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Empresa sobre a qual recai a transação
     * </pre>
     *
     * <code>string company = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCompanyBytes() {
      java.lang.Object ref = company_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        company_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QTD_FIELD_NUMBER = 3;
    private int qtd_;
    /**
     * <pre>
     * Número de acções a comprar 
     * </pre>
     *
     * <code>int32 qtd = 3;</code>
     */
    public int getQtd() {
      return qtd_;
    }

    public static final int PRICE_FIELD_NUMBER = 4;
    private int price_;
    /**
     * <pre>
     * Preço de compra máximo nas ordens de compra.
     *Preço de compra mínimo nas ordens de venda.
     * </pre>
     *
     * <code>int32 price = 4;</code>
     */
    public int getPrice() {
      return price_;
    }

    public static final int USERNAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object username_;
    /**
     * <pre>
     * Username de quem fez o pedido
     * </pre>
     *
     * <code>string username = 5;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Username de quem fez o pedido
     * </pre>
     *
     * <code>string username = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (orderType_ != protobuf.order.Order.OrderRequestType.BUY.getNumber()) {
        output.writeEnum(1, orderType_);
      }
      if (!getCompanyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, company_);
      }
      if (qtd_ != 0) {
        output.writeInt32(3, qtd_);
      }
      if (price_ != 0) {
        output.writeInt32(4, price_);
      }
      if (!getUsernameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, username_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (orderType_ != protobuf.order.Order.OrderRequestType.BUY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, orderType_);
      }
      if (!getCompanyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, company_);
      }
      if (qtd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, qtd_);
      }
      if (price_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, price_);
      }
      if (!getUsernameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, username_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.order.Order.OrderRequestData)) {
        return super.equals(obj);
      }
      protobuf.order.Order.OrderRequestData other = (protobuf.order.Order.OrderRequestData) obj;

      boolean result = true;
      result = result && orderType_ == other.orderType_;
      result = result && getCompany()
          .equals(other.getCompany());
      result = result && (getQtd()
          == other.getQtd());
      result = result && (getPrice()
          == other.getPrice());
      result = result && getUsername()
          .equals(other.getUsername());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ORDER_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + orderType_;
      hash = (37 * hash) + COMPANY_FIELD_NUMBER;
      hash = (53 * hash) + getCompany().hashCode();
      hash = (37 * hash) + QTD_FIELD_NUMBER;
      hash = (53 * hash) + getQtd();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getPrice();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.order.Order.OrderRequestData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.order.Order.OrderRequestData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.order.Order.OrderRequestData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.order.Order.OrderRequestData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.order.Order.OrderRequestData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.order.Order.OrderRequestData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.order.Order.OrderRequestData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.order.Order.OrderRequestData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.order.Order.OrderRequestData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.order.Order.OrderRequestData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.order.Order.OrderRequestData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.order.Order.OrderRequestData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.order.Order.OrderRequestData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     *Mensagem a ser enviada nas ordens de compra e venda.
     * </pre>
     *
     * Protobuf type {@code order.OrderRequestData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:order.OrderRequestData)
        protobuf.order.Order.OrderRequestDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.order.Order.internal_static_order_OrderRequestData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.order.Order.internal_static_order_OrderRequestData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.order.Order.OrderRequestData.class, protobuf.order.Order.OrderRequestData.Builder.class);
      }

      // Construct using protobuf.order.Order.OrderRequestData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        orderType_ = 0;

        company_ = "";

        qtd_ = 0;

        price_ = 0;

        username_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.order.Order.internal_static_order_OrderRequestData_descriptor;
      }

      public protobuf.order.Order.OrderRequestData getDefaultInstanceForType() {
        return protobuf.order.Order.OrderRequestData.getDefaultInstance();
      }

      public protobuf.order.Order.OrderRequestData build() {
        protobuf.order.Order.OrderRequestData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.order.Order.OrderRequestData buildPartial() {
        protobuf.order.Order.OrderRequestData result = new protobuf.order.Order.OrderRequestData(this);
        result.orderType_ = orderType_;
        result.company_ = company_;
        result.qtd_ = qtd_;
        result.price_ = price_;
        result.username_ = username_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.order.Order.OrderRequestData) {
          return mergeFrom((protobuf.order.Order.OrderRequestData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.order.Order.OrderRequestData other) {
        if (other == protobuf.order.Order.OrderRequestData.getDefaultInstance()) return this;
        if (other.orderType_ != 0) {
          setOrderTypeValue(other.getOrderTypeValue());
        }
        if (!other.getCompany().isEmpty()) {
          company_ = other.company_;
          onChanged();
        }
        if (other.getQtd() != 0) {
          setQtd(other.getQtd());
        }
        if (other.getPrice() != 0) {
          setPrice(other.getPrice());
        }
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.order.Order.OrderRequestData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.order.Order.OrderRequestData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int orderType_ = 0;
      /**
       * <pre>
       * Tipo da transação 
       * </pre>
       *
       * <code>.order.OrderRequestType order_type = 1;</code>
       */
      public int getOrderTypeValue() {
        return orderType_;
      }
      /**
       * <pre>
       * Tipo da transação 
       * </pre>
       *
       * <code>.order.OrderRequestType order_type = 1;</code>
       */
      public Builder setOrderTypeValue(int value) {
        orderType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Tipo da transação 
       * </pre>
       *
       * <code>.order.OrderRequestType order_type = 1;</code>
       */
      public protobuf.order.Order.OrderRequestType getOrderType() {
        protobuf.order.Order.OrderRequestType result = protobuf.order.Order.OrderRequestType.valueOf(orderType_);
        return result == null ? protobuf.order.Order.OrderRequestType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Tipo da transação 
       * </pre>
       *
       * <code>.order.OrderRequestType order_type = 1;</code>
       */
      public Builder setOrderType(protobuf.order.Order.OrderRequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        orderType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Tipo da transação 
       * </pre>
       *
       * <code>.order.OrderRequestType order_type = 1;</code>
       */
      public Builder clearOrderType() {
        
        orderType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object company_ = "";
      /**
       * <pre>
       * Empresa sobre a qual recai a transação
       * </pre>
       *
       * <code>string company = 2;</code>
       */
      public java.lang.String getCompany() {
        java.lang.Object ref = company_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          company_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Empresa sobre a qual recai a transação
       * </pre>
       *
       * <code>string company = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCompanyBytes() {
        java.lang.Object ref = company_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          company_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Empresa sobre a qual recai a transação
       * </pre>
       *
       * <code>string company = 2;</code>
       */
      public Builder setCompany(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        company_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Empresa sobre a qual recai a transação
       * </pre>
       *
       * <code>string company = 2;</code>
       */
      public Builder clearCompany() {
        
        company_ = getDefaultInstance().getCompany();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Empresa sobre a qual recai a transação
       * </pre>
       *
       * <code>string company = 2;</code>
       */
      public Builder setCompanyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        company_ = value;
        onChanged();
        return this;
      }

      private int qtd_ ;
      /**
       * <pre>
       * Número de acções a comprar 
       * </pre>
       *
       * <code>int32 qtd = 3;</code>
       */
      public int getQtd() {
        return qtd_;
      }
      /**
       * <pre>
       * Número de acções a comprar 
       * </pre>
       *
       * <code>int32 qtd = 3;</code>
       */
      public Builder setQtd(int value) {
        
        qtd_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Número de acções a comprar 
       * </pre>
       *
       * <code>int32 qtd = 3;</code>
       */
      public Builder clearQtd() {
        
        qtd_ = 0;
        onChanged();
        return this;
      }

      private int price_ ;
      /**
       * <pre>
       * Preço de compra máximo nas ordens de compra.
       *Preço de compra mínimo nas ordens de venda.
       * </pre>
       *
       * <code>int32 price = 4;</code>
       */
      public int getPrice() {
        return price_;
      }
      /**
       * <pre>
       * Preço de compra máximo nas ordens de compra.
       *Preço de compra mínimo nas ordens de venda.
       * </pre>
       *
       * <code>int32 price = 4;</code>
       */
      public Builder setPrice(int value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Preço de compra máximo nas ordens de compra.
       *Preço de compra mínimo nas ordens de venda.
       * </pre>
       *
       * <code>int32 price = 4;</code>
       */
      public Builder clearPrice() {
        
        price_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <pre>
       * Username de quem fez o pedido
       * </pre>
       *
       * <code>string username = 5;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Username de quem fez o pedido
       * </pre>
       *
       * <code>string username = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Username de quem fez o pedido
       * </pre>
       *
       * <code>string username = 5;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Username de quem fez o pedido
       * </pre>
       *
       * <code>string username = 5;</code>
       */
      public Builder clearUsername() {
        
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Username de quem fez o pedido
       * </pre>
       *
       * <code>string username = 5;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        username_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:order.OrderRequestData)
    }

    // @@protoc_insertion_point(class_scope:order.OrderRequestData)
    private static final protobuf.order.Order.OrderRequestData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.order.Order.OrderRequestData();
    }

    public static protobuf.order.Order.OrderRequestData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderRequestData>
        PARSER = new com.google.protobuf.AbstractParser<OrderRequestData>() {
      public OrderRequestData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderRequestData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderRequestData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderRequestData> getParserForType() {
      return PARSER;
    }

    public protobuf.order.Order.OrderRequestData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OrderReplyDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:order.OrderReplyData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Tipo da transação 
     * </pre>
     *
     * <code>.order.OrderReplyType reply_type = 1;</code>
     */
    int getReplyTypeValue();
    /**
     * <pre>
     * Tipo da transação 
     * </pre>
     *
     * <code>.order.OrderReplyType reply_type = 1;</code>
     */
    protobuf.order.Order.OrderReplyType getReplyType();
  }
  /**
   * <pre>
   **
   *Mensagem a ser enviada nas ordens de compra e venda.
   * </pre>
   *
   * Protobuf type {@code order.OrderReplyData}
   */
  public  static final class OrderReplyData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:order.OrderReplyData)
      OrderReplyDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OrderReplyData.newBuilder() to construct.
    private OrderReplyData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderReplyData() {
      replyType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OrderReplyData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              replyType_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.order.Order.internal_static_order_OrderReplyData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.order.Order.internal_static_order_OrderReplyData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.order.Order.OrderReplyData.class, protobuf.order.Order.OrderReplyData.Builder.class);
    }

    public static final int REPLY_TYPE_FIELD_NUMBER = 1;
    private int replyType_;
    /**
     * <pre>
     * Tipo da transação 
     * </pre>
     *
     * <code>.order.OrderReplyType reply_type = 1;</code>
     */
    public int getReplyTypeValue() {
      return replyType_;
    }
    /**
     * <pre>
     * Tipo da transação 
     * </pre>
     *
     * <code>.order.OrderReplyType reply_type = 1;</code>
     */
    public protobuf.order.Order.OrderReplyType getReplyType() {
      protobuf.order.Order.OrderReplyType result = protobuf.order.Order.OrderReplyType.valueOf(replyType_);
      return result == null ? protobuf.order.Order.OrderReplyType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (replyType_ != protobuf.order.Order.OrderReplyType.OK.getNumber()) {
        output.writeEnum(1, replyType_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (replyType_ != protobuf.order.Order.OrderReplyType.OK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, replyType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.order.Order.OrderReplyData)) {
        return super.equals(obj);
      }
      protobuf.order.Order.OrderReplyData other = (protobuf.order.Order.OrderReplyData) obj;

      boolean result = true;
      result = result && replyType_ == other.replyType_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REPLY_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + replyType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.order.Order.OrderReplyData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.order.Order.OrderReplyData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.order.Order.OrderReplyData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.order.Order.OrderReplyData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.order.Order.OrderReplyData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.order.Order.OrderReplyData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.order.Order.OrderReplyData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.order.Order.OrderReplyData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.order.Order.OrderReplyData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.order.Order.OrderReplyData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.order.Order.OrderReplyData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.order.Order.OrderReplyData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.order.Order.OrderReplyData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     *Mensagem a ser enviada nas ordens de compra e venda.
     * </pre>
     *
     * Protobuf type {@code order.OrderReplyData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:order.OrderReplyData)
        protobuf.order.Order.OrderReplyDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.order.Order.internal_static_order_OrderReplyData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.order.Order.internal_static_order_OrderReplyData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.order.Order.OrderReplyData.class, protobuf.order.Order.OrderReplyData.Builder.class);
      }

      // Construct using protobuf.order.Order.OrderReplyData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        replyType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.order.Order.internal_static_order_OrderReplyData_descriptor;
      }

      public protobuf.order.Order.OrderReplyData getDefaultInstanceForType() {
        return protobuf.order.Order.OrderReplyData.getDefaultInstance();
      }

      public protobuf.order.Order.OrderReplyData build() {
        protobuf.order.Order.OrderReplyData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.order.Order.OrderReplyData buildPartial() {
        protobuf.order.Order.OrderReplyData result = new protobuf.order.Order.OrderReplyData(this);
        result.replyType_ = replyType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.order.Order.OrderReplyData) {
          return mergeFrom((protobuf.order.Order.OrderReplyData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.order.Order.OrderReplyData other) {
        if (other == protobuf.order.Order.OrderReplyData.getDefaultInstance()) return this;
        if (other.replyType_ != 0) {
          setReplyTypeValue(other.getReplyTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.order.Order.OrderReplyData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.order.Order.OrderReplyData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int replyType_ = 0;
      /**
       * <pre>
       * Tipo da transação 
       * </pre>
       *
       * <code>.order.OrderReplyType reply_type = 1;</code>
       */
      public int getReplyTypeValue() {
        return replyType_;
      }
      /**
       * <pre>
       * Tipo da transação 
       * </pre>
       *
       * <code>.order.OrderReplyType reply_type = 1;</code>
       */
      public Builder setReplyTypeValue(int value) {
        replyType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Tipo da transação 
       * </pre>
       *
       * <code>.order.OrderReplyType reply_type = 1;</code>
       */
      public protobuf.order.Order.OrderReplyType getReplyType() {
        protobuf.order.Order.OrderReplyType result = protobuf.order.Order.OrderReplyType.valueOf(replyType_);
        return result == null ? protobuf.order.Order.OrderReplyType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Tipo da transação 
       * </pre>
       *
       * <code>.order.OrderReplyType reply_type = 1;</code>
       */
      public Builder setReplyType(protobuf.order.Order.OrderReplyType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        replyType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Tipo da transação 
       * </pre>
       *
       * <code>.order.OrderReplyType reply_type = 1;</code>
       */
      public Builder clearReplyType() {
        
        replyType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:order.OrderReplyData)
    }

    // @@protoc_insertion_point(class_scope:order.OrderReplyData)
    private static final protobuf.order.Order.OrderReplyData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.order.Order.OrderReplyData();
    }

    public static protobuf.order.Order.OrderReplyData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderReplyData>
        PARSER = new com.google.protobuf.AbstractParser<OrderReplyData>() {
      public OrderReplyData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderReplyData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderReplyData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OrderReplyData> getParserForType() {
      return PARSER;
    }

    public protobuf.order.Order.OrderReplyData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_OrderRequestData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_OrderRequestData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_OrderReplyData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_OrderReplyData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013order.proto\022\005order\"~\n\020OrderRequestData" +
      "\022+\n\norder_type\030\001 \001(\0162\027.order.OrderReques" +
      "tType\022\017\n\007company\030\002 \001(\t\022\013\n\003qtd\030\003 \001(\005\022\r\n\005p" +
      "rice\030\004 \001(\005\022\020\n\010username\030\005 \001(\t\";\n\016OrderRep" +
      "lyData\022)\n\nreply_type\030\001 \001(\0162\025.order.Order" +
      "ReplyType*%\n\020OrderRequestType\022\007\n\003BUY\020\000\022\010" +
      "\n\004SELL\020\001*L\n\016OrderReplyType\022\006\n\002OK\020\000\022\n\n\006NO" +
      "T_OK\020\001\022\023\n\017INVALID_COMPANY\020\002\022\021\n\rNOT_LOGGE" +
      "D_IN\020\003B\027\n\016protobuf.orderB\005Orderb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_order_OrderRequestData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_order_OrderRequestData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_OrderRequestData_descriptor,
        new java.lang.String[] { "OrderType", "Company", "Qtd", "Price", "Username", });
    internal_static_order_OrderReplyData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_order_OrderReplyData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_OrderReplyData_descriptor,
        new java.lang.String[] { "ReplyType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
