// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdu.proto

package protobuf.pdus;

public final class Pdu {
  private Pdu() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PduFromClientOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pdus.PduFromClient)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.order.OrderRequestData order = 1;</code>
     */
    boolean hasOrder();
    /**
     * <code>.order.OrderRequestData order = 1;</code>
     */
    protobuf.order.Order.OrderRequestData getOrder();
    /**
     * <code>.order.OrderRequestData order = 1;</code>
     */
    protobuf.order.Order.OrderRequestDataOrBuilder getOrderOrBuilder();

    /**
     * <code>.auth.AuthRequest auth = 2;</code>
     */
    boolean hasAuth();
    /**
     * <code>.auth.AuthRequest auth = 2;</code>
     */
    protobuf.auth.Auth.AuthRequest getAuth();
    /**
     * <code>.auth.AuthRequest auth = 2;</code>
     */
    protobuf.auth.Auth.AuthRequestOrBuilder getAuthOrBuilder();

    public protobuf.pdus.Pdu.PduFromClient.RequestCase getRequestCase();
  }
  /**
   * Protobuf type {@code pdus.PduFromClient}
   */
  public  static final class PduFromClient extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pdus.PduFromClient)
      PduFromClientOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PduFromClient.newBuilder() to construct.
    private PduFromClient(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PduFromClient() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PduFromClient(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              protobuf.order.Order.OrderRequestData.Builder subBuilder = null;
              if (requestCase_ == 1) {
                subBuilder = ((protobuf.order.Order.OrderRequestData) request_).toBuilder();
              }
              request_ =
                  input.readMessage(protobuf.order.Order.OrderRequestData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((protobuf.order.Order.OrderRequestData) request_);
                request_ = subBuilder.buildPartial();
              }
              requestCase_ = 1;
              break;
            }
            case 18: {
              protobuf.auth.Auth.AuthRequest.Builder subBuilder = null;
              if (requestCase_ == 2) {
                subBuilder = ((protobuf.auth.Auth.AuthRequest) request_).toBuilder();
              }
              request_ =
                  input.readMessage(protobuf.auth.Auth.AuthRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((protobuf.auth.Auth.AuthRequest) request_);
                request_ = subBuilder.buildPartial();
              }
              requestCase_ = 2;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.pdus.Pdu.internal_static_pdus_PduFromClient_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.pdus.Pdu.internal_static_pdus_PduFromClient_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.pdus.Pdu.PduFromClient.class, protobuf.pdus.Pdu.PduFromClient.Builder.class);
    }

    private int requestCase_ = 0;
    private java.lang.Object request_;
    public enum RequestCase
        implements com.google.protobuf.Internal.EnumLite {
      ORDER(1),
      AUTH(2),
      REQUEST_NOT_SET(0);
      private final int value;
      private RequestCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static RequestCase valueOf(int value) {
        return forNumber(value);
      }

      public static RequestCase forNumber(int value) {
        switch (value) {
          case 1: return ORDER;
          case 2: return AUTH;
          case 0: return REQUEST_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public RequestCase
    getRequestCase() {
      return RequestCase.forNumber(
          requestCase_);
    }

    public static final int ORDER_FIELD_NUMBER = 1;
    /**
     * <code>.order.OrderRequestData order = 1;</code>
     */
    public boolean hasOrder() {
      return requestCase_ == 1;
    }
    /**
     * <code>.order.OrderRequestData order = 1;</code>
     */
    public protobuf.order.Order.OrderRequestData getOrder() {
      if (requestCase_ == 1) {
         return (protobuf.order.Order.OrderRequestData) request_;
      }
      return protobuf.order.Order.OrderRequestData.getDefaultInstance();
    }
    /**
     * <code>.order.OrderRequestData order = 1;</code>
     */
    public protobuf.order.Order.OrderRequestDataOrBuilder getOrderOrBuilder() {
      if (requestCase_ == 1) {
         return (protobuf.order.Order.OrderRequestData) request_;
      }
      return protobuf.order.Order.OrderRequestData.getDefaultInstance();
    }

    public static final int AUTH_FIELD_NUMBER = 2;
    /**
     * <code>.auth.AuthRequest auth = 2;</code>
     */
    public boolean hasAuth() {
      return requestCase_ == 2;
    }
    /**
     * <code>.auth.AuthRequest auth = 2;</code>
     */
    public protobuf.auth.Auth.AuthRequest getAuth() {
      if (requestCase_ == 2) {
         return (protobuf.auth.Auth.AuthRequest) request_;
      }
      return protobuf.auth.Auth.AuthRequest.getDefaultInstance();
    }
    /**
     * <code>.auth.AuthRequest auth = 2;</code>
     */
    public protobuf.auth.Auth.AuthRequestOrBuilder getAuthOrBuilder() {
      if (requestCase_ == 2) {
         return (protobuf.auth.Auth.AuthRequest) request_;
      }
      return protobuf.auth.Auth.AuthRequest.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestCase_ == 1) {
        output.writeMessage(1, (protobuf.order.Order.OrderRequestData) request_);
      }
      if (requestCase_ == 2) {
        output.writeMessage(2, (protobuf.auth.Auth.AuthRequest) request_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (protobuf.order.Order.OrderRequestData) request_);
      }
      if (requestCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (protobuf.auth.Auth.AuthRequest) request_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.pdus.Pdu.PduFromClient)) {
        return super.equals(obj);
      }
      protobuf.pdus.Pdu.PduFromClient other = (protobuf.pdus.Pdu.PduFromClient) obj;

      boolean result = true;
      result = result && getRequestCase().equals(
          other.getRequestCase());
      if (!result) return false;
      switch (requestCase_) {
        case 1:
          result = result && getOrder()
              .equals(other.getOrder());
          break;
        case 2:
          result = result && getAuth()
              .equals(other.getAuth());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (requestCase_) {
        case 1:
          hash = (37 * hash) + ORDER_FIELD_NUMBER;
          hash = (53 * hash) + getOrder().hashCode();
          break;
        case 2:
          hash = (37 * hash) + AUTH_FIELD_NUMBER;
          hash = (53 * hash) + getAuth().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.pdus.Pdu.PduFromClient parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.pdus.Pdu.PduFromClient parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.pdus.Pdu.PduFromClient parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.pdus.Pdu.PduFromClient parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.pdus.Pdu.PduFromClient parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.pdus.Pdu.PduFromClient parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.pdus.Pdu.PduFromClient parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.pdus.Pdu.PduFromClient parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.pdus.Pdu.PduFromClient parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.pdus.Pdu.PduFromClient parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.pdus.Pdu.PduFromClient parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.pdus.Pdu.PduFromClient parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.pdus.Pdu.PduFromClient prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pdus.PduFromClient}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pdus.PduFromClient)
        protobuf.pdus.Pdu.PduFromClientOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.pdus.Pdu.internal_static_pdus_PduFromClient_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.pdus.Pdu.internal_static_pdus_PduFromClient_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.pdus.Pdu.PduFromClient.class, protobuf.pdus.Pdu.PduFromClient.Builder.class);
      }

      // Construct using protobuf.pdus.Pdu.PduFromClient.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requestCase_ = 0;
        request_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.pdus.Pdu.internal_static_pdus_PduFromClient_descriptor;
      }

      public protobuf.pdus.Pdu.PduFromClient getDefaultInstanceForType() {
        return protobuf.pdus.Pdu.PduFromClient.getDefaultInstance();
      }

      public protobuf.pdus.Pdu.PduFromClient build() {
        protobuf.pdus.Pdu.PduFromClient result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.pdus.Pdu.PduFromClient buildPartial() {
        protobuf.pdus.Pdu.PduFromClient result = new protobuf.pdus.Pdu.PduFromClient(this);
        if (requestCase_ == 1) {
          if (orderBuilder_ == null) {
            result.request_ = request_;
          } else {
            result.request_ = orderBuilder_.build();
          }
        }
        if (requestCase_ == 2) {
          if (authBuilder_ == null) {
            result.request_ = request_;
          } else {
            result.request_ = authBuilder_.build();
          }
        }
        result.requestCase_ = requestCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.pdus.Pdu.PduFromClient) {
          return mergeFrom((protobuf.pdus.Pdu.PduFromClient)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.pdus.Pdu.PduFromClient other) {
        if (other == protobuf.pdus.Pdu.PduFromClient.getDefaultInstance()) return this;
        switch (other.getRequestCase()) {
          case ORDER: {
            mergeOrder(other.getOrder());
            break;
          }
          case AUTH: {
            mergeAuth(other.getAuth());
            break;
          }
          case REQUEST_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.pdus.Pdu.PduFromClient parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.pdus.Pdu.PduFromClient) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int requestCase_ = 0;
      private java.lang.Object request_;
      public RequestCase
          getRequestCase() {
        return RequestCase.forNumber(
            requestCase_);
      }

      public Builder clearRequest() {
        requestCase_ = 0;
        request_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          protobuf.order.Order.OrderRequestData, protobuf.order.Order.OrderRequestData.Builder, protobuf.order.Order.OrderRequestDataOrBuilder> orderBuilder_;
      /**
       * <code>.order.OrderRequestData order = 1;</code>
       */
      public boolean hasOrder() {
        return requestCase_ == 1;
      }
      /**
       * <code>.order.OrderRequestData order = 1;</code>
       */
      public protobuf.order.Order.OrderRequestData getOrder() {
        if (orderBuilder_ == null) {
          if (requestCase_ == 1) {
            return (protobuf.order.Order.OrderRequestData) request_;
          }
          return protobuf.order.Order.OrderRequestData.getDefaultInstance();
        } else {
          if (requestCase_ == 1) {
            return orderBuilder_.getMessage();
          }
          return protobuf.order.Order.OrderRequestData.getDefaultInstance();
        }
      }
      /**
       * <code>.order.OrderRequestData order = 1;</code>
       */
      public Builder setOrder(protobuf.order.Order.OrderRequestData value) {
        if (orderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          orderBuilder_.setMessage(value);
        }
        requestCase_ = 1;
        return this;
      }
      /**
       * <code>.order.OrderRequestData order = 1;</code>
       */
      public Builder setOrder(
          protobuf.order.Order.OrderRequestData.Builder builderForValue) {
        if (orderBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          orderBuilder_.setMessage(builderForValue.build());
        }
        requestCase_ = 1;
        return this;
      }
      /**
       * <code>.order.OrderRequestData order = 1;</code>
       */
      public Builder mergeOrder(protobuf.order.Order.OrderRequestData value) {
        if (orderBuilder_ == null) {
          if (requestCase_ == 1 &&
              request_ != protobuf.order.Order.OrderRequestData.getDefaultInstance()) {
            request_ = protobuf.order.Order.OrderRequestData.newBuilder((protobuf.order.Order.OrderRequestData) request_)
                .mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          if (requestCase_ == 1) {
            orderBuilder_.mergeFrom(value);
          }
          orderBuilder_.setMessage(value);
        }
        requestCase_ = 1;
        return this;
      }
      /**
       * <code>.order.OrderRequestData order = 1;</code>
       */
      public Builder clearOrder() {
        if (orderBuilder_ == null) {
          if (requestCase_ == 1) {
            requestCase_ = 0;
            request_ = null;
            onChanged();
          }
        } else {
          if (requestCase_ == 1) {
            requestCase_ = 0;
            request_ = null;
          }
          orderBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.order.OrderRequestData order = 1;</code>
       */
      public protobuf.order.Order.OrderRequestData.Builder getOrderBuilder() {
        return getOrderFieldBuilder().getBuilder();
      }
      /**
       * <code>.order.OrderRequestData order = 1;</code>
       */
      public protobuf.order.Order.OrderRequestDataOrBuilder getOrderOrBuilder() {
        if ((requestCase_ == 1) && (orderBuilder_ != null)) {
          return orderBuilder_.getMessageOrBuilder();
        } else {
          if (requestCase_ == 1) {
            return (protobuf.order.Order.OrderRequestData) request_;
          }
          return protobuf.order.Order.OrderRequestData.getDefaultInstance();
        }
      }
      /**
       * <code>.order.OrderRequestData order = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protobuf.order.Order.OrderRequestData, protobuf.order.Order.OrderRequestData.Builder, protobuf.order.Order.OrderRequestDataOrBuilder> 
          getOrderFieldBuilder() {
        if (orderBuilder_ == null) {
          if (!(requestCase_ == 1)) {
            request_ = protobuf.order.Order.OrderRequestData.getDefaultInstance();
          }
          orderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protobuf.order.Order.OrderRequestData, protobuf.order.Order.OrderRequestData.Builder, protobuf.order.Order.OrderRequestDataOrBuilder>(
                  (protobuf.order.Order.OrderRequestData) request_,
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        requestCase_ = 1;
        onChanged();;
        return orderBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          protobuf.auth.Auth.AuthRequest, protobuf.auth.Auth.AuthRequest.Builder, protobuf.auth.Auth.AuthRequestOrBuilder> authBuilder_;
      /**
       * <code>.auth.AuthRequest auth = 2;</code>
       */
      public boolean hasAuth() {
        return requestCase_ == 2;
      }
      /**
       * <code>.auth.AuthRequest auth = 2;</code>
       */
      public protobuf.auth.Auth.AuthRequest getAuth() {
        if (authBuilder_ == null) {
          if (requestCase_ == 2) {
            return (protobuf.auth.Auth.AuthRequest) request_;
          }
          return protobuf.auth.Auth.AuthRequest.getDefaultInstance();
        } else {
          if (requestCase_ == 2) {
            return authBuilder_.getMessage();
          }
          return protobuf.auth.Auth.AuthRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.auth.AuthRequest auth = 2;</code>
       */
      public Builder setAuth(protobuf.auth.Auth.AuthRequest value) {
        if (authBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          authBuilder_.setMessage(value);
        }
        requestCase_ = 2;
        return this;
      }
      /**
       * <code>.auth.AuthRequest auth = 2;</code>
       */
      public Builder setAuth(
          protobuf.auth.Auth.AuthRequest.Builder builderForValue) {
        if (authBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          authBuilder_.setMessage(builderForValue.build());
        }
        requestCase_ = 2;
        return this;
      }
      /**
       * <code>.auth.AuthRequest auth = 2;</code>
       */
      public Builder mergeAuth(protobuf.auth.Auth.AuthRequest value) {
        if (authBuilder_ == null) {
          if (requestCase_ == 2 &&
              request_ != protobuf.auth.Auth.AuthRequest.getDefaultInstance()) {
            request_ = protobuf.auth.Auth.AuthRequest.newBuilder((protobuf.auth.Auth.AuthRequest) request_)
                .mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          if (requestCase_ == 2) {
            authBuilder_.mergeFrom(value);
          }
          authBuilder_.setMessage(value);
        }
        requestCase_ = 2;
        return this;
      }
      /**
       * <code>.auth.AuthRequest auth = 2;</code>
       */
      public Builder clearAuth() {
        if (authBuilder_ == null) {
          if (requestCase_ == 2) {
            requestCase_ = 0;
            request_ = null;
            onChanged();
          }
        } else {
          if (requestCase_ == 2) {
            requestCase_ = 0;
            request_ = null;
          }
          authBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.auth.AuthRequest auth = 2;</code>
       */
      public protobuf.auth.Auth.AuthRequest.Builder getAuthBuilder() {
        return getAuthFieldBuilder().getBuilder();
      }
      /**
       * <code>.auth.AuthRequest auth = 2;</code>
       */
      public protobuf.auth.Auth.AuthRequestOrBuilder getAuthOrBuilder() {
        if ((requestCase_ == 2) && (authBuilder_ != null)) {
          return authBuilder_.getMessageOrBuilder();
        } else {
          if (requestCase_ == 2) {
            return (protobuf.auth.Auth.AuthRequest) request_;
          }
          return protobuf.auth.Auth.AuthRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.auth.AuthRequest auth = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protobuf.auth.Auth.AuthRequest, protobuf.auth.Auth.AuthRequest.Builder, protobuf.auth.Auth.AuthRequestOrBuilder> 
          getAuthFieldBuilder() {
        if (authBuilder_ == null) {
          if (!(requestCase_ == 2)) {
            request_ = protobuf.auth.Auth.AuthRequest.getDefaultInstance();
          }
          authBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protobuf.auth.Auth.AuthRequest, protobuf.auth.Auth.AuthRequest.Builder, protobuf.auth.Auth.AuthRequestOrBuilder>(
                  (protobuf.auth.Auth.AuthRequest) request_,
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        requestCase_ = 2;
        onChanged();;
        return authBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pdus.PduFromClient)
    }

    // @@protoc_insertion_point(class_scope:pdus.PduFromClient)
    private static final protobuf.pdus.Pdu.PduFromClient DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.pdus.Pdu.PduFromClient();
    }

    public static protobuf.pdus.Pdu.PduFromClient getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PduFromClient>
        PARSER = new com.google.protobuf.AbstractParser<PduFromClient>() {
      public PduFromClient parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PduFromClient(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PduFromClient> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PduFromClient> getParserForType() {
      return PARSER;
    }

    public protobuf.pdus.Pdu.PduFromClient getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pdus_PduFromClient_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pdus_PduFromClient_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tpdu.proto\022\004pdus\032\nauth.proto\032\013order.pro" +
      "to\"g\n\rPduFromClient\022(\n\005order\030\001 \001(\0132\027.ord" +
      "er.OrderRequestDataH\000\022!\n\004auth\030\002 \001(\0132\021.au" +
      "th.AuthRequestH\000B\t\n\007requestB\024\n\rprotobuf." +
      "pdusB\003Pdub\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protobuf.auth.Auth.getDescriptor(),
          protobuf.order.Order.getDescriptor(),
        }, assigner);
    internal_static_pdus_PduFromClient_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pdus_PduFromClient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pdus_PduFromClient_descriptor,
        new java.lang.String[] { "Order", "Auth", "Request", });
    protobuf.auth.Auth.getDescriptor();
    protobuf.order.Order.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
