// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package protobuf.auth;

public final class Auth {
  private Auth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   **
   *Indica se o cliente pretende fazer login ou logout.
   * </pre>
   *
   * Protobuf enum {@code auth.AuthRequestType}
   */
  public enum AuthRequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOGIN = 0;</code>
     */
    LOGIN(0),
    /**
     * <code>LOGOUT = 1;</code>
     */
    LOGOUT(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>LOGIN = 0;</code>
     */
    public static final int LOGIN_VALUE = 0;
    /**
     * <code>LOGOUT = 1;</code>
     */
    public static final int LOGOUT_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AuthRequestType valueOf(int value) {
      return forNumber(value);
    }

    public static AuthRequestType forNumber(int value) {
      switch (value) {
        case 0: return LOGIN;
        case 1: return LOGOUT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AuthRequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AuthRequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AuthRequestType>() {
            public AuthRequestType findValueByNumber(int number) {
              return AuthRequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protobuf.auth.Auth.getDescriptor().getEnumTypes().get(0);
    }

    private static final AuthRequestType[] VALUES = values();

    public static AuthRequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AuthRequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:auth.AuthRequestType)
  }

  /**
   * <pre>
   **
   *Indica se o utilizador pretende fazer login ou logout.
   * </pre>
   *
   * Protobuf enum {@code auth.AuthReplyType}
   */
  public enum AuthReplyType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Login ok 
     * </pre>
     *
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <pre>
     * Login falha por utilizador não existir 
     * </pre>
     *
     * <code>WRONG_USER = 1;</code>
     */
    WRONG_USER(1),
    /**
     * <pre>
     * Login falha por utilizador existir mas password estar errada 
     * </pre>
     *
     * <code>WRONG_PASSWORD = 2;</code>
     */
    WRONG_PASSWORD(2),
    /**
     * <pre>
     * Motivo de falha genérico.
     *Motivo desconhecido ou intencionalmente não indicado ao utilizador
     *por razões de segurança.  
     * </pre>
     *
     * <code>NOT_OK = 3;</code>
     */
    NOT_OK(3),
    /**
     * <pre>
     * O utilizador indicou uma operação que apenas pode fazer
     *se tiver o login feito
     * </pre>
     *
     * <code>NOT_LOGGED_IN = 4;</code>
     */
    NOT_LOGGED_IN(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Login ok 
     * </pre>
     *
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <pre>
     * Login falha por utilizador não existir 
     * </pre>
     *
     * <code>WRONG_USER = 1;</code>
     */
    public static final int WRONG_USER_VALUE = 1;
    /**
     * <pre>
     * Login falha por utilizador existir mas password estar errada 
     * </pre>
     *
     * <code>WRONG_PASSWORD = 2;</code>
     */
    public static final int WRONG_PASSWORD_VALUE = 2;
    /**
     * <pre>
     * Motivo de falha genérico.
     *Motivo desconhecido ou intencionalmente não indicado ao utilizador
     *por razões de segurança.  
     * </pre>
     *
     * <code>NOT_OK = 3;</code>
     */
    public static final int NOT_OK_VALUE = 3;
    /**
     * <pre>
     * O utilizador indicou uma operação que apenas pode fazer
     *se tiver o login feito
     * </pre>
     *
     * <code>NOT_LOGGED_IN = 4;</code>
     */
    public static final int NOT_LOGGED_IN_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AuthReplyType valueOf(int value) {
      return forNumber(value);
    }

    public static AuthReplyType forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return WRONG_USER;
        case 2: return WRONG_PASSWORD;
        case 3: return NOT_OK;
        case 4: return NOT_LOGGED_IN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AuthReplyType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AuthReplyType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AuthReplyType>() {
            public AuthReplyType findValueByNumber(int number) {
              return AuthReplyType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protobuf.auth.Auth.getDescriptor().getEnumTypes().get(1);
    }

    private static final AuthReplyType[] VALUES = values();

    public static AuthReplyType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AuthReplyType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:auth.AuthReplyType)
  }

  public interface AuthRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:auth.AuthRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.auth.AuthRequestType auth_type = 1;</code>
     */
    int getAuthTypeValue();
    /**
     * <code>.auth.AuthRequestType auth_type = 1;</code>
     */
    protobuf.auth.Auth.AuthRequestType getAuthType();

    /**
     * <code>string username = 2;</code>
     */
    java.lang.String getUsername();
    /**
     * <code>string username = 2;</code>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>string password = 3;</code>
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 3;</code>
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * <pre>
   **
   *Mensagem que será enviada num pedido de autenticação pelo cliente.
   *Tanto para fazer login como para fazer logout o utilizador deve indicar a password.
   * </pre>
   *
   * Protobuf type {@code auth.AuthRequest}
   */
  public  static final class AuthRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:auth.AuthRequest)
      AuthRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AuthRequest.newBuilder() to construct.
    private AuthRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AuthRequest() {
      authType_ = 0;
      username_ = "";
      password_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AuthRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              authType_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              username_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.auth.Auth.internal_static_auth_AuthRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.auth.Auth.internal_static_auth_AuthRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.auth.Auth.AuthRequest.class, protobuf.auth.Auth.AuthRequest.Builder.class);
    }

    public static final int AUTH_TYPE_FIELD_NUMBER = 1;
    private int authType_;
    /**
     * <code>.auth.AuthRequestType auth_type = 1;</code>
     */
    public int getAuthTypeValue() {
      return authType_;
    }
    /**
     * <code>.auth.AuthRequestType auth_type = 1;</code>
     */
    public protobuf.auth.Auth.AuthRequestType getAuthType() {
      protobuf.auth.Auth.AuthRequestType result = protobuf.auth.Auth.AuthRequestType.valueOf(authType_);
      return result == null ? protobuf.auth.Auth.AuthRequestType.UNRECOGNIZED : result;
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object username_;
    /**
     * <code>string username = 2;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <code>string username = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 3;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 3;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (authType_ != protobuf.auth.Auth.AuthRequestType.LOGIN.getNumber()) {
        output.writeEnum(1, authType_);
      }
      if (!getUsernameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, username_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (authType_ != protobuf.auth.Auth.AuthRequestType.LOGIN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, authType_);
      }
      if (!getUsernameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, username_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.auth.Auth.AuthRequest)) {
        return super.equals(obj);
      }
      protobuf.auth.Auth.AuthRequest other = (protobuf.auth.Auth.AuthRequest) obj;

      boolean result = true;
      result = result && authType_ == other.authType_;
      result = result && getUsername()
          .equals(other.getUsername());
      result = result && getPassword()
          .equals(other.getPassword());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AUTH_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + authType_;
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.auth.Auth.AuthRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.auth.Auth.AuthRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.auth.Auth.AuthRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.auth.Auth.AuthRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.auth.Auth.AuthRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.auth.Auth.AuthRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.auth.Auth.AuthRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.auth.Auth.AuthRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.auth.Auth.AuthRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.auth.Auth.AuthRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.auth.Auth.AuthRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.auth.Auth.AuthRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.auth.Auth.AuthRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     *Mensagem que será enviada num pedido de autenticação pelo cliente.
     *Tanto para fazer login como para fazer logout o utilizador deve indicar a password.
     * </pre>
     *
     * Protobuf type {@code auth.AuthRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:auth.AuthRequest)
        protobuf.auth.Auth.AuthRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.auth.Auth.internal_static_auth_AuthRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.auth.Auth.internal_static_auth_AuthRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.auth.Auth.AuthRequest.class, protobuf.auth.Auth.AuthRequest.Builder.class);
      }

      // Construct using protobuf.auth.Auth.AuthRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        authType_ = 0;

        username_ = "";

        password_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.auth.Auth.internal_static_auth_AuthRequest_descriptor;
      }

      public protobuf.auth.Auth.AuthRequest getDefaultInstanceForType() {
        return protobuf.auth.Auth.AuthRequest.getDefaultInstance();
      }

      public protobuf.auth.Auth.AuthRequest build() {
        protobuf.auth.Auth.AuthRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.auth.Auth.AuthRequest buildPartial() {
        protobuf.auth.Auth.AuthRequest result = new protobuf.auth.Auth.AuthRequest(this);
        result.authType_ = authType_;
        result.username_ = username_;
        result.password_ = password_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.auth.Auth.AuthRequest) {
          return mergeFrom((protobuf.auth.Auth.AuthRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.auth.Auth.AuthRequest other) {
        if (other == protobuf.auth.Auth.AuthRequest.getDefaultInstance()) return this;
        if (other.authType_ != 0) {
          setAuthTypeValue(other.getAuthTypeValue());
        }
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.auth.Auth.AuthRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.auth.Auth.AuthRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int authType_ = 0;
      /**
       * <code>.auth.AuthRequestType auth_type = 1;</code>
       */
      public int getAuthTypeValue() {
        return authType_;
      }
      /**
       * <code>.auth.AuthRequestType auth_type = 1;</code>
       */
      public Builder setAuthTypeValue(int value) {
        authType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.auth.AuthRequestType auth_type = 1;</code>
       */
      public protobuf.auth.Auth.AuthRequestType getAuthType() {
        protobuf.auth.Auth.AuthRequestType result = protobuf.auth.Auth.AuthRequestType.valueOf(authType_);
        return result == null ? protobuf.auth.Auth.AuthRequestType.UNRECOGNIZED : result;
      }
      /**
       * <code>.auth.AuthRequestType auth_type = 1;</code>
       */
      public Builder setAuthType(protobuf.auth.Auth.AuthRequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        authType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.auth.AuthRequestType auth_type = 1;</code>
       */
      public Builder clearAuthType() {
        
        authType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>string username = 2;</code>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string username = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string username = 2;</code>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string username = 2;</code>
       */
      public Builder clearUsername() {
        
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>string username = 2;</code>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        username_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 3;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 3;</code>
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 3;</code>
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 3;</code>
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:auth.AuthRequest)
    }

    // @@protoc_insertion_point(class_scope:auth.AuthRequest)
    private static final protobuf.auth.Auth.AuthRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.auth.Auth.AuthRequest();
    }

    public static protobuf.auth.Auth.AuthRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AuthRequest>
        PARSER = new com.google.protobuf.AbstractParser<AuthRequest>() {
      public AuthRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuthRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AuthRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuthRequest> getParserForType() {
      return PARSER;
    }

    public protobuf.auth.Auth.AuthRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AuthReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:auth.AuthReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.auth.AuthReplyType reply_type = 1;</code>
     */
    int getReplyTypeValue();
    /**
     * <code>.auth.AuthReplyType reply_type = 1;</code>
     */
    protobuf.auth.Auth.AuthReplyType getReplyType();
  }
  /**
   * Protobuf type {@code auth.AuthReply}
   */
  public  static final class AuthReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:auth.AuthReply)
      AuthReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AuthReply.newBuilder() to construct.
    private AuthReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AuthReply() {
      replyType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AuthReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              replyType_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.auth.Auth.internal_static_auth_AuthReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.auth.Auth.internal_static_auth_AuthReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.auth.Auth.AuthReply.class, protobuf.auth.Auth.AuthReply.Builder.class);
    }

    public static final int REPLY_TYPE_FIELD_NUMBER = 1;
    private int replyType_;
    /**
     * <code>.auth.AuthReplyType reply_type = 1;</code>
     */
    public int getReplyTypeValue() {
      return replyType_;
    }
    /**
     * <code>.auth.AuthReplyType reply_type = 1;</code>
     */
    public protobuf.auth.Auth.AuthReplyType getReplyType() {
      protobuf.auth.Auth.AuthReplyType result = protobuf.auth.Auth.AuthReplyType.valueOf(replyType_);
      return result == null ? protobuf.auth.Auth.AuthReplyType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (replyType_ != protobuf.auth.Auth.AuthReplyType.OK.getNumber()) {
        output.writeEnum(1, replyType_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (replyType_ != protobuf.auth.Auth.AuthReplyType.OK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, replyType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.auth.Auth.AuthReply)) {
        return super.equals(obj);
      }
      protobuf.auth.Auth.AuthReply other = (protobuf.auth.Auth.AuthReply) obj;

      boolean result = true;
      result = result && replyType_ == other.replyType_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REPLY_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + replyType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.auth.Auth.AuthReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.auth.Auth.AuthReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.auth.Auth.AuthReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.auth.Auth.AuthReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.auth.Auth.AuthReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.auth.Auth.AuthReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.auth.Auth.AuthReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.auth.Auth.AuthReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.auth.Auth.AuthReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.auth.Auth.AuthReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.auth.Auth.AuthReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.auth.Auth.AuthReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.auth.Auth.AuthReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code auth.AuthReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:auth.AuthReply)
        protobuf.auth.Auth.AuthReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.auth.Auth.internal_static_auth_AuthReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.auth.Auth.internal_static_auth_AuthReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.auth.Auth.AuthReply.class, protobuf.auth.Auth.AuthReply.Builder.class);
      }

      // Construct using protobuf.auth.Auth.AuthReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        replyType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.auth.Auth.internal_static_auth_AuthReply_descriptor;
      }

      public protobuf.auth.Auth.AuthReply getDefaultInstanceForType() {
        return protobuf.auth.Auth.AuthReply.getDefaultInstance();
      }

      public protobuf.auth.Auth.AuthReply build() {
        protobuf.auth.Auth.AuthReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.auth.Auth.AuthReply buildPartial() {
        protobuf.auth.Auth.AuthReply result = new protobuf.auth.Auth.AuthReply(this);
        result.replyType_ = replyType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.auth.Auth.AuthReply) {
          return mergeFrom((protobuf.auth.Auth.AuthReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.auth.Auth.AuthReply other) {
        if (other == protobuf.auth.Auth.AuthReply.getDefaultInstance()) return this;
        if (other.replyType_ != 0) {
          setReplyTypeValue(other.getReplyTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.auth.Auth.AuthReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.auth.Auth.AuthReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int replyType_ = 0;
      /**
       * <code>.auth.AuthReplyType reply_type = 1;</code>
       */
      public int getReplyTypeValue() {
        return replyType_;
      }
      /**
       * <code>.auth.AuthReplyType reply_type = 1;</code>
       */
      public Builder setReplyTypeValue(int value) {
        replyType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.auth.AuthReplyType reply_type = 1;</code>
       */
      public protobuf.auth.Auth.AuthReplyType getReplyType() {
        protobuf.auth.Auth.AuthReplyType result = protobuf.auth.Auth.AuthReplyType.valueOf(replyType_);
        return result == null ? protobuf.auth.Auth.AuthReplyType.UNRECOGNIZED : result;
      }
      /**
       * <code>.auth.AuthReplyType reply_type = 1;</code>
       */
      public Builder setReplyType(protobuf.auth.Auth.AuthReplyType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        replyType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.auth.AuthReplyType reply_type = 1;</code>
       */
      public Builder clearReplyType() {
        
        replyType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:auth.AuthReply)
    }

    // @@protoc_insertion_point(class_scope:auth.AuthReply)
    private static final protobuf.auth.Auth.AuthReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.auth.Auth.AuthReply();
    }

    public static protobuf.auth.Auth.AuthReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AuthReply>
        PARSER = new com.google.protobuf.AbstractParser<AuthReply>() {
      public AuthReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuthReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AuthReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuthReply> getParserForType() {
      return PARSER;
    }

    public protobuf.auth.Auth.AuthReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_AuthRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_AuthRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_AuthReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_AuthReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nauth.proto\022\004auth\"[\n\013AuthRequest\022(\n\taut" +
      "h_type\030\001 \001(\0162\025.auth.AuthRequestType\022\020\n\010u" +
      "sername\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\"4\n\tAuthR" +
      "eply\022\'\n\nreply_type\030\001 \001(\0162\023.auth.AuthRepl" +
      "yType*(\n\017AuthRequestType\022\t\n\005LOGIN\020\000\022\n\n\006L" +
      "OGOUT\020\001*Z\n\rAuthReplyType\022\006\n\002OK\020\000\022\016\n\nWRON" +
      "G_USER\020\001\022\022\n\016WRONG_PASSWORD\020\002\022\n\n\006NOT_OK\020\003" +
      "\022\021\n\rNOT_LOGGED_IN\020\004B\025\n\rprotobuf.authB\004Au" +
      "thb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_auth_AuthRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_auth_AuthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_AuthRequest_descriptor,
        new java.lang.String[] { "AuthType", "Username", "Password", });
    internal_static_auth_AuthReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_auth_AuthReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_AuthReply_descriptor,
        new java.lang.String[] { "ReplyType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
