%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.1

-ifndef(auth).
-define(auth, true).

-define(auth_gpb_version, "4.1.1").

-ifndef('AUTHREQUEST_PB_H').
-define('AUTHREQUEST_PB_H', true).
-record('AuthRequest',
        {auth_type = 'LOGIN'    :: 'LOGIN' | 'LOGOUT' | integer() | undefined, % = 1, enum AuthRequestType
         username = []          :: iolist() | undefined, % = 2
         password = []          :: iolist() | undefined % = 3
        }).
-endif.

-ifndef('AUTHREPLY_PB_H').
-define('AUTHREPLY_PB_H', true).
-record('AuthReply',
        {reply_type = 'OK'      :: 'OK' | 'WRONG_USER' | 'WRONG_PASSWORD' | 'NOT_OK' | 'NOT_LOGGED_IN' | integer() | undefined % = 1, enum AuthReplyType
        }).
-endif.

-endif.
