%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.1

-ifndef(order).
-define(order, true).

-define(order_gpb_version, "4.1.1").

-ifndef('ORDERREQUESTDATA_PB_H').
-define('ORDERREQUESTDATA_PB_H', true).
-record('OrderRequestData',
        {order_type = 'BUY'     :: 'BUY' | 'SELL' | integer() | undefined, % = 1, enum OrderRequestType
         company = []           :: iolist() | undefined, % = 2
         qtd = 0                :: integer() | undefined, % = 3, 32 bits
         price = 0              :: integer() | undefined, % = 4, 32 bits
         username = []          :: iolist() | undefined % = 5
        }).
-endif.

-ifndef('ORDERREPLYDATA_PB_H').
-define('ORDERREPLYDATA_PB_H', true).
-record('OrderReplyData',
        {reply_type = 'OK'      :: 'OK' | 'NOT_OK' | 'INVALID_COMPANY' | 'NOT_LOGGED_IN' | integer() | undefined % = 1, enum OrderReplyType
        }).
-endif.

-endif.
