%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.1

-ifndef(pdu).
-define(pdu, true).

-define(pdu_gpb_version, "4.1.1").

-ifndef('ORDERREQUESTDATA_PB_H').
-define('ORDERREQUESTDATA_PB_H', true).
-record('OrderRequestData',
        {order_type = 'BUY'     :: 'BUY' | 'SELL' | integer() | undefined, % = 1, enum OrderRequestType
         company = []           :: iolist() | undefined, % = 2
         qtd = 0                :: integer() | undefined, % = 3, 32 bits
         price = 0              :: integer() | undefined, % = 4, 32 bits
         username = []          :: iolist() | undefined % = 5
        }).
-endif.

-ifndef('AUTHREPLY_PB_H').
-define('AUTHREPLY_PB_H', true).
-record('AuthReply',
        {reply_type = 'OK'      :: 'OK' | 'WRONG_USER' | 'WRONG_PASSWORD' | 'NOT_OK' | 'NOT_LOGGED_IN' | integer() | undefined % = 1, enum AuthReplyType
        }).
-endif.

-ifndef('ORDERREPLYDATA_PB_H').
-define('ORDERREPLYDATA_PB_H', true).
-record('OrderReplyData',
        {reply_type = 'OK'      :: 'OK' | 'NOT_OK' | 'INVALID_COMPANY' | 'NOT_LOGGED_IN' | integer() | undefined % = 1, enum OrderReplyType
        }).
-endif.

-ifndef('AUTHREQUEST_PB_H').
-define('AUTHREQUEST_PB_H', true).
-record('AuthRequest',
        {auth_type = 'LOGIN'    :: 'LOGIN' | 'LOGOUT' | integer() | undefined, % = 1, enum AuthRequestType
         username = []          :: iolist() | undefined, % = 2
         password = []          :: iolist() | undefined % = 3
        }).
-endif.

-ifndef('PDUFROMCLIENT_PB_H').
-define('PDUFROMCLIENT_PB_H', true).
-record('PduFromClient',
        {request                :: {order, #'OrderRequestData'{}} | {auth, #'AuthRequest'{}} | undefined % oneof
        }).
-endif.

-endif.
